server:
    port: 8081
    servlet:
        context-path: /filmes-api
    error:
        include-stacktrace: never

spring:
    profiles:
        active: dev
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://${DB_HOST:localhost}:3306/filmesdb
        username: filmesuser
        password: filmespass
    jpa:
        show-sql: true
        properties:
            hibernate:
                format_sql: false
                transaction:
                    jta:
                        platform: false
