services:
    moviesdb-serv:
        image: mariadb:10.11
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MARIADB_DATABASE=moviesdb
            - MARIADB_USER=${MARIADB_USER}
            - MARIADB_PASSWORD=${MARIADB_PASS}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASS}
            - TZ=America/Fortaleza
        volumes:
            - ${HOST_MARIADB_VOLUME}:/var/lib/mysql
        expose:
            - 3306
        networks:
            - movies-net

#    movies-api:
#        image: rodneybarreto/movies-api:0.0.1
#        restart: always
#        environment:
#            - LOG_PATH=./logs
#            - PORT=8081
#            - TZ=America/Fortaleza
#            - DB_HOST=moviesdb-serv
#        volumes:
#            - "./logs:/opt/movies-api/logs"
#        ports:
#            - "8081:8081"
#        depends_on:
#            - moviesdb-serv
#        networks:
#            - movies-net

networks:
    movies-net:
        driver: bridge