services:
    filmesdb-serv:
        image: mariadb:10.11
        restart: always
        ports:
            - "3306:3306"
        environment:
            - MARIADB_DATABASE=filmesdb
            - MARIADB_USER=filmesuser
            - MARIADB_PASSWORD=filmespass
            - MARIADB_ROOT_PASSWORD=admin@123
            - TZ=America/Sao_Paulo
        volumes:
            - /home/rodney/databases/mariadb:/var/lib/mysql
        expose:
            - 3306
        networks:
            - filmes-net

#    filmes-api:
#        image: rodneybarreto/filmes-api:0.0.1
#        restart: always
#        environment:
#            - LOG_PATH=./logs
#            - PORT=8081
#            - TZ=America/Sao_Paulo
#            - DB_HOST=filmesdb-serv
#        volumes:
#            - "./logs:/opt/filmes-api/logs"
#        ports:
#            - "8081:8081"
#        depends_on:
#            - filmesdb-serv
#        networks:
#            - filmes-net

networks:
    filmes-net:
        driver: bridge